### PR TITLE
Adds a locator to locate tenant codes from cookies

### PR DESCRIPTION
**Pull request by Brunty**
It checks the tenant registry and doesn't allow access to dev or test as tenants, just in case.

### CODE REVIEW

**Comment by Brunty** [comment]
Failing tests are the same as per this comment: https://github.com/vivait/TenantBundle/pull/16#issuecomment-151601690

**Comment by Brunty** [comment]
Having looked at this, will require more work to find a way to get production to be allowed and then it'll set the tenant in a cookie based on some sort of GET parameter for the first load.

**Comment by Brunty** [comment]
Though, potentially the application implementing the cookie locator could have a route that it'd run via the production environment, there it could set the cookie (after verifying that the GET parameter is valid for the tenant in the config, and then redirect to the start page where a tenant cookie would be in place)

**Comment by leightonthomas** [comment]
:+1:  Looks good to me

**Pull request merged**
